#!/bin/sh

# This can be done at runtime if role mapped to plan.
# Select statement must be predefined/ttls need to be predefined
# Roles need to be predefined.

VAULT_ADDR=http://$1:8200 vault secrets enable -path=cloudify/binder/mariadb kv
VAULT_ADDR=http://$1:8200 vault write cloudify/binder/mariadb config='{"__credoutputs__":["mysql_ip"],"__credpath__": "database/creds/my-role", "__path__": "database/config/vault_test","plugin_name": "mysql-database-plugin","connection_url": "demo:new_password@tcp({{["mysql_ip"]}})/", "allowed_roles": "my-role", "username": "demo", "password": "new_password" }'
