apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mariadb-instance
  namespace: test-ns
spec:
  clusterServiceClassExternalName: mariadb
  clusterServicePlanExternalName: default
  parameters:
    network_deployment_name: openstack-network

